data_paths:
  text: "examples/data/text.json"
  image: "examples/data/figure.json"
  table: "examples/data/table.json"
  formula: "examples/data/formula.json"
  title: ""
work_path:
  template_path: "templates"
  template_file: "three_columns/document.html.jinja"
  template_get_data: "three_columns/getData"
  html_dir: "working/html"
  save_image_dir: "working/image"
  output_gt_dir: "working/ground_truth"
  result: "results.json"
defaults:
  save_path: "Temp"
  save_every_n: 4

layout_config:
  element:
    table: 2
    figure: 1
    title: 0
    text: 8
    formula: 0
    header: 0
    footer: 0
    page_footnote: 0
  columns: 3  # 可通过 --columns 1/2/3 覆盖

num_workers: 3
nums: 3
